redis:
  uri: "redis://127.0.0.1/"

exchanges:
  - name: "binance"
    symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "LTCUSDT", "AVAXUSDT", "DOTUSDT", "BNBUSDT"]

  - name: "bybit"
    symbols: ["BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "LTCUSDT", "AVAXUSDT", "DOTUSDT", "BNBUSDT"]

  - name: "kraken"
    symbols: ["BTC/USD", "ETH/USD", "SOL/USD", "XRP/USD", "DOGE/USD", "ADA/USD", "LTC/USD", "AVAX/USD", "DOT/USD", "BNB/USD"]

  - name: "hyperliquid"
    symbols: ["BTC", "ETH", "SOL", "XRP", "ADA"]
